# *********************************************************
# Thank you for using this plugin! <3
# Author: Matistan
# If you enjoy this plugin, please rate it on spigotmc.org:
# https://www.spigotmc.org/resources/death-swap.109401/
# *********************************************************

# Set to true to set the time to day automatically when the game starts.
timeSetDayOnStart: true
# Set to true to set the weather to clear automatically when the game starts.
weatherClearOnStart: true
# Set to true to take away OPs for the duration of the game.
takeAwayOps: true
# Set to true to clear players inventories when the game starts.
clearInventories: true
# Set the time for a swap (10sec - 3600sec).
time: 300
# Set the maximum time that can be added or subtracted from the time (time must be always between 10sec - 3600sec).
varyingTime: 0
# Set to true to enable PvP during the match.
pvpEnabled: false
# Set to true to show scoreboard with the timer.
scoreboard: true
# Set to true to enable permission checks.
## Note: This feature needs a permissions plugin (such as LuckPerms) to work.
usePermissions: false